# Generated by Django 2.2 on 2019-04-10 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionMachines', '0002_auto_20190409_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('disponible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire', to=settings.AUTH_USER_MODEL)),
                ('utilisateur_actuel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
