# Generated by Django 2.2 on 2019-04-10 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMachines', '0003_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='utilisateur_actuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='utilisateur', to=settings.AUTH_USER_MODEL),
        ),
    ]
