# Generated by Django 2.2 on 2019-04-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMachines', '0004_auto_20190410_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='photo',
            field=models.ImageField(null=True, upload_to='machines'),
        ),
    ]
